### PR TITLE
Simplify ivy-postframe-avy

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by tumashu** [comment]
merged, thanks very much!

**Comment by noctuid** [comment]
This brings back one of the bugs where ivy-posframe starts showing nothing after using `ivy-posframe-avy` in different frames. I was using `with-current-buffer` as opposed to `with-selected-window` to get around this before ([see this comment](https://github.com/tumashu/ivy-posframe/issues/6#issuecomment-449092933)).

**Comment by tumashu** [comment]
This? https://github.com/tumashu/ivy-posframe/pull/19/commits/187d14b3567c1b9d1cde0bbcd7308c30f068f85e

**Comment by tumashu** [comment]
@noctuid I have invited you as ivy-posframe's collaborator,  just update or revert it :-)

**Comment by noctuid** [comment]
I'd prefer if it was possible to just call `ivy-avy` directly without issues. I will look into this issue further when I have some time.

**Comment by tumashu** [comment]
Today, I try abo-abo's pr in msys2-emacs26 of window7, seem to work ok for new make-frame, are you using MacOS's emacs? @noctuid

**Comment by noctuid** [comment]
I'm using Linux and emacs 27.

**Comment by tumashu** [comment]
Gnome? or other WM?
```
where ivy-posframe starts showing nothing after using ivy-posframe-avy in different frames.
```
Could you have time to recode a Gif for this problem?

**Comment by noctuid** [comment]
I'm using bspwm and no DE.

The issue only happens for me after moving a frame to a new desktop, or unmapping it, or doing something else with it. For example, these steps cause the issue for me:
1. Call `ivy-switch-buffer` and use `ivy-posframe-avy`
2. Create a new frame with `make-frame-command`
3. Move the new frame to a different desktop and go to that desktop/frame

All subsequent `ivy-switch-buffer`s will just show a blank posframe on either frame.

I still need to find a minimal reproduction for this; it's quite possibly some issue with my config. I will bisect my config and get back to you.

**Comment by noctuid** [comment]
I was able to get a minimal reproduction. The issue is caused by `(setq scroll-conservatively 20)` in my config. Setting it to 0 immediately fixes the issue immediately. It is blank because it gets scrolled past all candidates.

I have other issues even with `scroll-conservatively` set to 0 and without making new frames. After callying `ivy-posframe-avy` once, subseqent ivy posframe commands will not show the prompt and will show lower candidates. There's probably some easy way to prevent scrolling in the posframe window, which seems to be the issue here.

**Comment by tumashu** [comment]
I think this problem is created by this function:
```
(defun ivy--avy-candidates ()
  (let (candidates)
    (save-excursion
      (save-restriction
        (narrow-to-region
         (window-start)
         (window-end))
        (goto-char (point-min))
        (forward-line)
        (while (< (point) (point-max))
          (push
           (cons (point)
                 (selected-window))
           candidates)
          (forward-line))))
    (nreverse candidates)))
```

for ivy-posframe, I do not think this is a good aproach to get candidate, for
ivy-posframe's window size is determined by posframe-show's :string argument,
what about just parse :string?

**Comment by tumashu** [comment]
I have tested, and find the same problem, when I set (setq scroll-conservatively 20)  and press <down> to scroll ivy menu down, the prompt will dispear, maybe force set scroll-conservatively to 0 for ivy-posframe?

**Comment by tumashu** [comment]
图片

**Comment by tumashu** [comment]
This problem should be fixed, please see: https://github.com/tumashu/posframe/commit/3eaf066ae8e7bea89ac347c095c7fb7b8d42fcbd

**Comment by noctuid** [comment]
:+1: Works as expected

**Pull request merged**
