### PR TITLE
Fix ivy-posframe--posframe-p-advice function

### PR DESCRIPTION
**Pull request by conao3**
As PR #53 has merged, This PR code has some modifications in terms of coding style.

Also, in my experience, I have never encountered a situation where I give advice to an advice function. This can interfere with later code reading.

I'm still wondering if we really need advice on those advice function, but if we need it, I'd rather write a conditional branch for every advice function instead of the current tricky way.

### CODE REVIEW

**Comment by conao3** [comment]
There is room for discussion as to whether this function's name, `(ivy-posframe--)posframe-p-advice`, is suitable.
This advice is, in other words, checking whether it makes advice functions enable or not, isn't it?

**Comment by conao3** [comment]
And `posframe` has `posframe-workable-p` in https://github.com/tumashu/posframe/blob/fc90a1a558200e5c3688c65add9afdea695a2c10/posframe.el#L190 .
Can this function be used to determine the condition?

**Comment by tumashu** [comment]
The only strength oe two step advice is  short code :-)

```
I'd rather write a conditional branch for every advice function instead of the current tricky way.
```
I agree this is more simple to understand, but code seem to look unbeautiful,
What about add a macro to create advice function?

**Comment by conao3** [comment]
OK! I agree with your point. I create another PR.

**Pull request closed without merging**
